#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["WebApil2/WebApil2.csproj", "WebApil2/"]
RUN dotnet restore "WebApil2/WebApil2.csproj"
COPY . .
WORKDIR "/src/WebApil2"
RUN dotnet build "WebApil2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApil2.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApil2.dll"]