apiVersion: v1
kind: Service
metadata:
  name: pod1-webapi2-service
  namespace: k8s-poc
spec:
  selector:
    app: pod1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: pod1-webapi3-service
  namespace: k8s-poc
spec:
  selector:
    app: pod1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
      nodePort: 30081